# Generated by Django 5.0.6 on 2024-07-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='customers',
            name='city',
            field=models.CharField(default='Unknown', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customers',
            name='zipcode',
            field=models.CharField(default='Unknown', max_length=30),
            preserve_default=False,
        ),
    ]
