# Generated by Django 5.0.6 on 2024-07-19 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0002_rename_first_name_customers_firstname_customers_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='username',
        ),
    ]
